### ISSUE TITLE
Use 3rd party downloaders

### ISSUE THREAD

**Issue by cyan-2048** [Aliucord/plugin-requests#106] opened 2021-07-26 11:17 UTC
### Discord Account

Cyan#0101

### Plugin Description

 ~~or just a way to copy the url of files/attachments sent in discord~~
yeah sorry for being dumb this was already made it seems 

 coz im a dumbass that uses 1DM+, and i also like downloading files to my sdcard

### Go into more detail...

idk i want it to work just like the option in firefox

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by keanuplayz** [comment] 2021-07-26 11:21
Duplicate of #102?

**Comment by NatSepruko** [comment] 2021-07-26 11:24
Related to #102 but not a direct copy of, as they also requested for a plugin that allows you to use external apps for downloading attachments.

**Closed** 2023-08-28 01:48 UTC
Labels: up for grabs
