### ISSUE TITLE
rename attachments before sending them like on pc

### ISSUE THREAD

**Issue by quiet69** [Aliucord/plugin-requests#472] opened 2021-12-22 09:18 UTC
### Discord Account

quiet#0069

### Plugin Description

A plugin which lets us rename or randomise name of attachment of pictures and videos before uploading

### Go into more detail...

That's it

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by scrazzz** [comment] 2021-12-22 09:41
Duplicate of #327

Please don't lie that you checked to make sure that your plugin request is original.

**Closed** 2021-12-22 09:42 UTC
Labels: up for grabs

**Comment by quiet69** [comment] 2021-12-22 09:50
I apologise... I didn't scroll too far...

**Comment by scrazzz** [comment] 2021-12-22 09:52
![guh](https://user-images.githubusercontent.com/70033559/147073164-ed59b079-a18f-49d0-bc73-aea24a370c25.jpg)
