### ISSUE TITLE
Anonymized file name

### ISSUE THREAD

**Issue by Eve9181** [Aliucord/plugin-requests#1248] opened 2023-11-30 03:58 UTC
### Plugin Description

A plug-in that automatically changes file name to random letter or just untitled

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by jedenastka** [comment] 2024-02-15 02:27
Duplicate of #1127.

**Closed as not planned** 2024-02-15 10:54 UTC
