### ISSUE TITLE
Read all message button

### ISSUE THREAD

**Issue by ahihiyou20** [Aliucord/plugin-requests#477] opened 2021-12-27 00:55 UTC
### Discord Account

@Ogiwara Sayu#3784 

### Plugin Description

Add a button. If you press it then it will read all message for you (_or just add slash command_)

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by ItzOnlyAnimal** [comment] 2021-12-27 00:59
1. Duplicate of #55 and many others
2. it needs to be implemented correctly to not be selfbot behavior

**Closed** 2021-12-27 01:31 UTC
Labels: up for grabs
