### ISSUE TITLE
pinDMs

### ISSUE THREAD

**Issue by lolpowerluke** [Aliucord/plugin-requests#84] opened 2021-07-10 07:03 UTC
### Discord Account

lolpowerluke#5364

### Plugin Description

Allows you to pin DMs, making them appear at the top of your DMs/ServerList

### Go into more detail...

the pinDMs plugin from betterdiscord made for aliucord

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by MulverineX** [comment] 2021-07-10 07:05
https://github.com/powercord-community/betterfriends

**Comment by WinstonSepruko** [comment] 2021-07-10 07:06
Duplicate of #35

**Closed by WinstonSepruko** 2021-07-10 07:06 UTC
Labels: up for grabs
