### ISSUE TITLE
ANSI discord mobile

### ISSUE THREAD

**Issue by cr1ptik** [Aliucord/plugin-requests#844] opened 2022-04-15 07:13 UTC
### Plugin Description

add the ANSI markdown to mobile. kinda useless I guess but it's sexy 
https://gist.github.com/kkrypt0nn/a02506f3712ff2d1c8ca7c9e0aed7c06

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by scrazzz** [comment] 2022-04-15 07:19
"[x] I did indeed check to make sure my plugin request is original!"

Duplicate of #662

**Closed** 2022-04-15 18:40 UTC
Labels: up for grabs
