### ISSUE TITLE
Polls

### ISSUE THREAD

**Issue by Noraxx1** [Aliucord/plugin-requests#1361] opened 2024-04-20 19:37 UTC
### Plugin Description

A plugin to read and create discord polls

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by jedenastka** [comment] 2024-04-20 19:52
Duplicate of #1327.

**Closed as not planned** 2024-04-21 01:52 UTC
