### ISSUE TITLE
making a custom name for someone

### ISSUE THREAD

**Issue by tuleo1** [Aliucord/plugin-requests#65] opened 2021-06-27 21:27 UTC
### Discord Account

kairoio#0001

### Plugin Description

so basically it would be pretty cool to make a nickname to a specific person.

### Go into more detail...

so for example if I have a friend that in dms or server his name is "kairo" I could use this plugin and change his name to let's say "pie" so in the server chat or in dms it'll show "pie" instead of "kairo"

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by WinstonSepruko** [comment] 2021-06-27 21:34
Closed as duplicate of #42.

**Closed** 2021-06-27 21:34 UTC
Labels: up for grabs
