### ISSUE TITLE
EditUsers

### ISSUE THREAD

**Issue by Minacat1** [Aliucord/plugin-requests#455] opened 2021-12-17 22:48 UTC
### Discord Account

SuKanzoo#8931

### Plugin Description

Allows you to locally edit Users

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Juby210** [comment] 2021-12-17 22:49
duplicate of #423. Stop making issues without checking first.

**Closed by Juby210** 2021-12-17 22:49 UTC
Labels: up for grabs
