### ISSUE TITLE
Message search by date

### ISSUE THREAD

**Issue by KaKi87** [Aliucord/plugin-requests#185] opened 2021-08-24 16:27 UTC
### Discord Account

KaKi87#2368

### Plugin Description

Allow searching messages by date on mobile like it is natively possible on desktop.

### Go into more detail...

Thanks !

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by dmack6464** [comment] 2021-08-24 16:31
Another PC/web feature that could go into the same plugin, searching with user snowflakes (from:324260038736871426 etc...)

**Comment by Vendicated** [comment] 2021-08-24 16:37
Duplicate of #72

**Closed by Vendicated** 2021-08-24 16:37 UTC
Labels: up for grabs
