### ISSUE TITLE
Add time filter to search options

### ISSUE THREAD

**Issue by Likver** [Aliucord/plugin-requests#842] opened 2022-04-14 12:36 UTC
### Plugin Description

An option that lets u find a message setting the exact time u want, so if i want to see a message from 1 month ago i can easily find it

*im not 100% sure if this is original*

### Go into more detail...

itsñ could be nice if u could set the starting day and the last u want to search for (idk how to explain)

basically if u want to see messages from apr 10 to apr 13 then just set apr 10 as the starting day to 13 to show msgs only from 10 to 13

i hope u understood me

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by zt64** [comment] 2022-04-14 13:16
Duplicate of #72

**Closed** 2022-04-14 13:16 UTC
Labels: up for grabs
