### ISSUE TITLE
Custom status

### ISSUE THREAD

**Issue by FbiBoss** [Aliucord/plugin-requests#387] opened 2021-11-15 18:58 UTC
### Discord Account

FBI_BOSS¹⁴⁰#6281

### Plugin Description

Custom status playing,streaming,watching....

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by terabyte25** [comment] 2021-11-15 18:59
Duplicate of #97

**Comment by scrazzz** [comment] 2021-11-15 19:44
Also duplicate of #211

**Closed** 2021-11-15 20:21 UTC
Labels: up for grabs
