### ISSUE TITLE
Soundboard plugin

### ISSUE THREAD

**Issue by ghost** [Aliucord/plugin-requests#1299] opened 2024-02-18 20:34 UTC
### Plugin Description

A plugin that allows us to use all server soundboard sounds in any call. (Everyone must be able to hear it)

### Go into more detail...

Seems no one responded to the past requests (made by other users) so I'm assuming they weren't see by the right people, so I'm posting this in hopes the feed will get the attention of the right people.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by jedenastka** [comment] 2024-02-18 20:55
> I did indeed check to make sure my plugin request is original!

*That was a damn lie.*

Duplicate of #1225.

**Closed as not planned** 2024-02-18 21:01 UTC

**Comment by ghost** [comment] 2024-03-09 17:32
No, it wasn't. I checked as far back as the forum went. No other suggestions were about this. Somewhat similar, as it mentioned a soundboard, but not at all what I asked for. 

I will say, that apparently after searching the keyword of "soundboard", I didn't have that request shown. I was shown 3 requests. None of them were that one. I'm not sure why I wasn't shown that one, but I did not lie.

**Comment by jedenastka** [comment] 2024-03-09 17:34
> Seems no one responded to the past requests (made by other users) so I'm assuming they weren't see by the right people, so I'm posting this in hopes the feed will get the attention of the right people.

**Comment by ghost** [comment] 2024-03-09 17:38
Oh, I thought this was another post forum. Yeah, no, it's original by loophole sense. Just not the sense you were asking for. That's fair though.
