### ISSUE TITLE
Show profile badges next to the username

### ISSUE THREAD

**Issue by LittleDogPog** [Aliucord/plugin-requests#463] opened 2021-12-19 13:43 UTC
### Plugin Description

A plugin that shows the users badges next to his username will be very useful because it will look cool and modern.

### Go into more detail...

The plugin should show the users badges next to his username in chat, dms, and member list.
For example if a user has nitro badge and hypesquad balance, in the chat, dms, and member list should look like this:
"Username (badge icons)"
The bagdes should be the same size as the username.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment] 2021-12-19 14:07
This gets you rate limited so you occasionally can't load people's mutual servers and banner/bio

**Comment by Juby210** [comment] 2021-12-19 15:14
Duplicate of #191

**Closed by Juby210** 2021-12-19 15:14 UTC
Labels: up for grabs
