### ISSUE TITLE
shortcut for delete message button

### ISSUE THREAD

**Issue by bozohi** [Aliucord/plugin-requests#649] opened 2022-02-21 13:45 UTC
### Plugin Description

just make a shortcut for deleting messages button, nothing much

### Go into more detail...

ą

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by scrazzz** [comment] 2022-03-26 09:06
Duplicate of #560 ~~and #2.
Ven pls check #2 and implement it to TapTap~~

**Closed** 2022-04-02 15:17 UTC
Labels: duplicate
