### ISSUE TITLE
Plugin Polls Support

### ISSUE THREAD

**Issue by AloneTravers** [Aliucord/plugin-requests#1352] opened 2024-04-12 11:22 UTC
### Discord Account

dabloon/alon0000

### Plugin Description

New discord version, (**especially beta ones**) added support to the polls, it would be much appreciated if there's plugin to see, or even interact with it.

### Go into more detail...

Being able to interact/see with the polls with the Aliucord discord modification.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by jedenastka** [comment] 2024-04-12 13:37
~~Already tracked at https://github.com/Aliucord/Aliucord/issues/442.~~

Duplicate of #1327.

**Closed as not planned** 2024-04-12 15:29 UTC
