### ISSUE TITLE
EditUsersLocally

### ISSUE THREAD

**Issue by Juliaxe** [Aliucord/plugin-requests#423] opened 2021-12-02 07:18 UTC
### Discord Account

Juliaxe#1058

### Plugin Description

Like EditServersLocally but for users.

Edit profile pictures, profile banners, usernames, user tags (#1234), about me's, roles, and more.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Juby210** [comment] 2021-12-17 22:50
duplicate of #42

**Closed by Juby210** 2021-12-17 22:50 UTC
Labels: up for grabs
