### ISSUE TITLE
Input audio switcher

### ISSUE THREAD

**Issue by myrajurek** [Aliucord/plugin-requests#1280] opened 2024-01-02 07:04 UTC
### Plugin Description

Discord currently has the option to switch output devices during a call or vc, but does not have the same option for input devices and defaults to whatever your device mic is. 
I'm proposing a plugin that would enable you to change your input device so that you can change it to connected headsets ect. 

### Go into more detail...

Just create a context menu similar to the output devices selection on the call menu and add a section in the settings menu in audio and call, where you could set your default input device and (if possible idk) input volume similar to desktop. 

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by jedenastka** [comment] 2024-02-21 13:21
Duplicate of #151.

**Closed as not planned** 2024-02-21 20:44 UTC
