### ISSUE TITLE
Badgeseverywhere 

### ISSUE THREAD

**Issue by legendarymsr** [Aliucord/plugin-requests#708] opened 2022-03-21 08:38 UTC
### Discord Account

Legendarymaster#8657 

### Plugin Description

It would be cool if you could see badges everywhere like on bd 

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by taskylizard** [comment] 2022-03-21 08:42
Duplicate of #191.

**Closed** 2022-03-21 08:46 UTC
Labels: up for grabs
