### ISSUE TITLE
AnonymiseFileNames

### ISSUE THREAD

**Issue by Crisp-Casper** [Aliucord/plugin-requests#1337] opened 2024-03-28 04:50 UTC
### Plugin Description

When you upload a file randomize the name before uploading has been done already for vencord

### Go into more detail...

Vencord version https://vencord.dev/plugins/AnonymiseFileNames

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Crisp-Casper** [comment] 2024-03-28 04:52
There is code at this link idk if the import would be easy https://github.com/Vendicated/Vencord/blob/main/src/plugins/anonymiseFileNames/index.tsx

**Comment by jedenastka** [comment] 2024-03-28 16:28
Duplicate of #1127.

**Closed as not planned** 2024-03-28 16:31 UTC
