### ISSUE TITLE
Rich presence

### ISSUE THREAD

**Issue by Mittu129384** [Aliucord/plugin-requests#603] opened 2022-01-29 05:56 UTC
### Discord Account

Riu#3000

### Plugin Description

So there is a plugin named rich presence which is available for better discord (pc) is it possible for mobile 
![Uploading custom-rich-presence-discord-16edit(1).jpg…]()

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by zt64** [comment] 2022-01-29 06:22
Duplicate of #97

**Closed** 2022-01-29 13:10 UTC
Labels: up for grabs
