### ISSUE TITLE
Double tap to reply.

### ISSUE THREAD

**Issue by keanuplayz** [Aliucord/plugin-requests#39] opened 2021-06-03 15:09 UTC
### Description
Double tap a message to reply to it.

### More info
Replying to a message is rather swift, but it can be made even quicker by merely double tapping the message you want to reply to.

- [x] I checked if this plugin wasn't already requested.

**Comment by Juby210** [comment] 2021-06-03 15:16
Duplicate of #2

**Closed by Juby210** 2021-06-03 15:16 UTC
Labels: up for grabs
