### ISSUE TITLE
Favorite GIFs or Images

### ISSUE THREAD

**Issue by Zayan-Husain** [Aliucord/plugin-requests#1210] opened 2023-09-29 19:26 UTC
### Discord Account

boredomisnotafk

### Plugin Description

Basically you know how you can favorite GIFs on desktop discord? I want that on Aliucord except you dont have to convert an image to a gif, you can just favorite either GIFs or Images. This makes it easier to post an image or a gif when necessary. For example if theres an advice post that happens all the time, you can make an image or gif that you can post easily every time a similar post occurs.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by totaltommygun** [comment] 2024-01-26 09:32
Shouldn't this be native to Aliucord since Discord for mobile has already had this feature for over a year now? its a real feature some of my friends can't live without so it seems strange to me why its just a plugin request, but I'm not a Dev so idk how complicated it would be, but it just seems very strange from a users pov.

https://github.com/Aliucord/Aliucord/issues/418#issue-2101817358

https://www.reddit.com/r/discordapp/comments/z6rcoc/discord_finally_added_favorite_gifs_to_mobile/

**Comment by Slimemaster0** [comment] 2024-02-14 13:38
No this is not in Aliucord since it was added in Alpha 156.5 and Aliucord is based on 126.21 stable.

**Comment by Apethesis** [comment] 2024-02-14 14:04
Would it be difficult to backport then?

**Comment by Slimemaster0** [comment] 2024-02-14 16:00
I don't think its that hard to implement, however thats besed on the quantaty of features.

This plugin might be relevant: [Vendetta Faverite gifs](https://github.com/castdrian/vendetta-plugins/tree/main/plugins/favorite-gifs). (it would not work for aliucord however it could be used as a refrence)

**Comment by jedenastka** [comment] 2024-11-02 12:49
Duplicate of #417.

**Closed as not planned by jedenastka** 2024-11-02 12:49 UTC
