### ISSUE TITLE
Copy links from audio files

### ISSUE THREAD

**Issue by br4zyy** [Aliucord/plugin-requests#705] opened 2022-03-20 03:10 UTC
### Discord Account

brazy#9346

### Plugin Description

a plugin that shows a button to copy the link to an audio file when you long press the audio file

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by A-rhyna-H** [comment] 2022-03-20 03:13
view raw?

**Comment by br4zyy** [comment] 2022-03-20 03:35
> view raw?

wdym

**Comment by A-rhyna-H** [comment] 2022-03-20 03:36
ViewRaw plugin gets you link for any uploaded file

**Comment by Vendicated** [comment] 2022-03-20 04:12
Duplicate of #67

**Closed by Vendicated** 2022-03-20 04:12 UTC
Labels: up for grabs
