### ISSUE TITLE
Secret-Servers

### ISSUE THREAD

**Issue by Asimoposting** [Aliucord/plugin-requests#555] opened 2022-01-18 14:11 UTC
### Discord Account

Asimo#2810

### Plugin Description

A plugin that hides servers from discord, for seeing the server you need to go to a menu or putting a password

### Go into more detail...

There should be a menu that makes you enter the password for entering the server

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by scrazzz** [comment] 2022-01-24 11:23
Somewhat a duplicate of #520

**Closed** 2023-08-28 02:27 UTC
Labels: duplicate
