### ISSUE TITLE
Plugins for Tablet UI Improvement

### ISSUE THREAD

**Issue by Garumu** [Aliucord/plugin-requests#687] opened 2022-03-08 11:34 UTC
### Discord Account

MisheruP#6371

### Plugin Description

It would be great to see plugins that are used to improve the UI on a tablet device, since it only uses a scuffed version of the mobile UI.

Maybe even make it look like the Desktop UI as well!

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment] 2022-03-08 11:41
Duplicate of #382

**Closed by Vendicated** 2022-03-08 11:41 UTC
Labels: up for grabs
