### ISSUE TITLE
GuildAndFriendRemovalAlerts

### ISSUE THREAD

**Issue by Minacat1** [Aliucord/plugin-requests#454] opened 2021-12-17 22:45 UTC
### Discord Account

SuKanzoo#8931

### Plugin Description

Displays alerts when you are kicked/banned from a server, a server is deleted, and when a friend removes you.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Juby210** [comment] 2021-12-17 22:48
duplicate of #284

**Closed by Juby210** 2021-12-17 22:48 UTC
Labels: up for grabs
