### ISSUE TITLE
IphoneEmoji

### ISSUE THREAD

**Issue by rqlic** [Aliucord/plugin-requests#1441] opened 2024-10-21 13:49 UTC
### Discord Account

.rqlic.

### Plugin Description

A plugin which would turn all the normal emojis to the one which iphone has. Basically changing the appearance of the normal emojis to make it look like you are viewing it from an iphone.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by jedenastka** [comment] 2024-11-14 11:31
Duplicate of #22.

**Closed as not planned by jedenastka** 2024-11-14 11:31 UTC
