### ISSUE TITLE
locally edit message 

### ISSUE THREAD

**Issue by nearop** [Aliucord/plugin-requests#428] opened 2021-12-06 10:40 UTC
### Discord Account

RaFiN#6276

### Plugin Description

make pulgin like we can edit someone message locally​ 

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by scrazzz** [comment] 2021-12-06 10:47
Duplicate of #407

**Closed** 2021-12-06 12:28 UTC
Labels: duplicate
