### ISSUE TITLE
Chat GPT API

### ISSUE THREAD

**Issue by luhvmelody** [Aliucord/plugin-requests#1061] opened 2023-05-15 02:11 UTC
### Discord Account

mintpuddle#9847

### Plugin Description

A plugin to add a chat gpt-linked client bot for quick information! 

### Go into more detail...

I know theres already an API bot, but we all know chatgpt is pretty cool. Just make it to where you can do like /chatgpt and ask a question or smnthn. Itd be pretty cool.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment] 2023-05-30 17:47
future ref: https://github.com/xtekky/gpt4free

**Comment by WitherredAway** [comment] 2023-06-01 10:18
maybe clyde support will be a better idea

**Comment by OmegaSunkey** [comment] 2023-09-03 23:26
duplicate of #1034

**Closed as completed by OmegaSunkey** 2023-09-03 23:26 UTC
Labels: up for grabs
