### ISSUE TITLE
GhostMessage/GhostPing

### ISSUE THREAD

**Issue by iprisj** [Aliucord/plugin-requests#678] opened 2022-03-04 05:08 UTC
### Discord Account

prisj#0001

### Plugin Description

Send a message then delete it in {interval}. Can include a ping or just a normal message. 

### Go into more detail...

Time interval on how long it takes to delete after sending. 

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by zt64** [comment] 2022-03-04 05:25
Duplicate of #556

**Closed** 2022-03-04 05:26 UTC
Labels: up for grabs
