### ISSUE TITLE
Super reactions

### ISSUE THREAD

**Issue by Nivgab** [Aliucord/plugin-requests#1430] opened 2024-09-13 15:53 UTC
### Discord Account

secment

### Plugin Description

Add super reactions for nitro users

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by zt64** [comment] 2024-09-13 21:45
Duplicate of #1219

**Closed as not planned by zt64** 2024-09-13 21:45 UTC
