### ISSUE TITLE
Change download path

### ISSUE THREAD

**Issue by n00b69** [Aliucord/plugin-requests#1097] opened 2023-06-07 08:52 UTC
### Discord Account

the sog#6658

### Plugin Description

The ability to change the download path that is used to store images/videos saved inside the Discord app. 

When using an SD card, two download paths exist on your phone. One that is located on the SD card and is used by every other app, and then there's Discord that uses the unused download path in the internal storage. If Discord could use the SD card one it would be much better.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by jedenastka** [comment] 2024-11-01 02:35
[ChangeDownloadPath](https://gitlab.com/Grzesiek11/changedownloadpath-aliucord-plugin) is now available.

**Comment by jedenastka** [comment] 2024-11-01 09:49
Also, apparently a duplicate of #884.

**Closed as not planned** 2024-11-01 09:48 UTC
