### ISSUE TITLE
Follow Button on own Announcement Channels

### ISSUE THREAD

**Issue by Dennis-2002-YT** [Aliucord/plugin-requests#533] opened 2022-01-15 09:00 UTC
### Discord Account

Dennis 2002#3836

### Plugin Description

As a Server Admin I always need to open the Browser Tab on my phone if I want to add my own announcement Channel to other servers. This could be changed with a plugin so I can do this without browser tab

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Therealloli101** [comment] 2022-01-15 10:20
Was already requested

**Comment by Juby210** [comment] 2022-01-15 18:45
duplicate of #79

**Closed by Juby210** 2022-01-15 18:45 UTC
Labels: up for grabs
