### ISSUE TITLE
Hide massages

### ISSUE THREAD

**Issue by Randy-Light** [Aliucord/plugin-requests#684] opened 2022-03-06 21:41 UTC
### Plugin Description

Hide massages from selected users, for example I don't want to ban them i just don't wanna see their massages on server

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by saintwithataint** [comment] 2022-03-13 04:29
you can block them

**Comment by danlok10** [comment] 2022-03-13 07:50
Custom status
Like Playing (something)
Or Watching (something)
And etc

**Comment by Randy-Light** [comment] 2022-03-13 07:52
> you can block them

Yes, but i don't wanna let them know that they in block. I just wanna make it like a full ignore

**Comment by neko-astolfo-uwu** [comment] 2022-03-13 07:52
> Custom status
> Like Playing (something)
> Or Watching (something)
> And etc

No, there wont be an RPC plugin and dont comment with new requests below an already existing request.

**Comment by Vendicated** [comment] 2022-03-13 14:23
duplicate of #9

**Closed by Vendicated** 2022-03-13 14:23 UTC
Labels: up for grabs
