### ISSUE TITLE
MP3

### ISSUE THREAD

**Issue by GrazePossum** [Aliucord/plugin-requests#143] opened 2021-08-10 18:31 UTC
### Plugin Description

Let the mobile app play mp3,wav etc like on pc

### Go into more detail...

It should let you have the mp3 player when somebody sends one instead of just allowing you to save it then open it

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Juby210** [comment] 2021-08-10 18:32
duplicate of #105

**Closed by Juby210** 2021-08-10 18:32 UTC
Labels: up for grabs
