### ISSUE TITLE
Larger text from #

### ISSUE THREAD

**Issue by Jordanbytoto** [Aliucord/plugin-requests#1234] opened 2023-10-22 12:00 UTC
### Discord Account

@felixkjeilberg

### Plugin Description

Import the feature from base discord that makes the text larger and bolds it if you add a hashtag before it

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by ThatOneCalculator** [comment] 2023-11-05 03:39
Duplicate of #1071

**Closed as not planned** 2023-11-05 03:42 UTC
