### ISSUE TITLE
Making webhooks

### ISSUE THREAD

**Issue by Sussybakauwu69** [Aliucord/plugin-requests#212] opened 2021-09-07 12:57 UTC
### Plugin Description

What if aliucord could make webhooks?

### Go into more detail...

Because webhooks are a thing and idk why discord wont let mobile users be able to make webhooks.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by hairyfred** [comment] 2021-09-07 13:03
This is probs more a discord request not an Aliucord request
But ill leave the request open

**Comment by ArjixWasTaken** [comment] 2021-09-17 11:27
What you are talking about is embeds.
Anyone can send a webhook to a channel as long as that channel has an endpoint that receives webhooks.

That means that unless you have permissions to edit a channel, you cannot send a webhook.
It's entirely possible to send embeds, but they are detectable and can cause your discord account to be banned.
Now, that was about sending embeds, but you can use an external site that embeds that data you want, in other words the user will send a link and it won't make it detectable by discord.

A plugin like that exists in both better discord and powercord, iirc its named safe embed generator.
So anyone that wants to do this should look at those plugins (for their rest apis).

**Comment by Vendicated** [comment] 2021-09-17 11:35
they just want to be able to create webhooks which you can't do on mobile for some reason

**Comment by ArjixWasTaken** [comment] 2021-09-17 11:39
> they just want to be able to create webhooks which you can't do on mobile for some reason

Oh!
My bad, yeah, so it's about adding the option in the channel settings.
Ok, ignore my original message.

**Comment by Juby210** [comment] 2021-09-26 19:38
duplicate of #125

**Closed by Juby210** 2021-09-26 19:38 UTC
Labels: up for grabs
