### ISSUE TITLE
Edit Users

### ISSUE THREAD

**Issue by HypedDomi** [Aliucord/plugin-requests#69] opened 2021-06-30 23:30 UTC
### Discord Account

HypedDomi#1711

### Plugin Description

A plugin to edit local the users. Like pfp, name, badges, banner

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by keanuplayz** [comment] 2021-06-30 23:32
Duplicate of #42.

**Closed** 2021-06-30 23:34 UTC
Labels: up for grabs

**Comment by Bderdev** [comment] 2022-01-18 19:35
I approve!

**Comment by Bderdev** [comment] 2022-01-18 19:35
Seems pretty good.

**Comment by Juby210** [comment] 2022-01-18 19:36
> Seems pretty good.

Please avoid useless comments. Read:
https://github.com/Aliucord/plugin-requests/blob/main/README.md#i-really-want-x-plugin-but-i-dont-know-how-to-make-it

**Comment by Asimoposting** [comment] 2022-01-18 19:38
Hehe funny number
