### ISSUE TITLE
older message searcher

### ISSUE THREAD

**Issue by SparklyBubbly** [Aliucord/plugin-requests#1031] opened 2022-05-23 13:48 UTC
### Discord Account

SparklyBubbly#5024

### Plugin Description

A plugin that lets search messages like in pc, letting you toggle between looking from older messages to newer and newer to older

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Juby210** [comment] 2023-05-04 21:58
Duplicate of #72

**Closed by Juby210** 2023-05-04 21:58 UTC
Labels: up for grabs
