### ISSUE TITLE
Add new discord formating

### ISSUE THREAD

**Issue by GrandisPL** [Aliucord/plugin-requests#1176] opened 2023-08-29 20:55 UTC
### Discord Account

_grandis

### Plugin Description

I think it would be cool to have a plugin that allows users to see bix text (# something) it makes the text bigger in new discord. ^^
![Screenshot_20230829-225413_Discord](https://github.com/Aliucord/plugin-requests/assets/132256696/0ef8fca9-c6ad-47ad-8eae-1a2e5b32ecf8)

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by jedenastka** [comment] 2024-02-15 02:04
Duplicate of #1071.

**Closed as not planned** 2024-02-15 02:19 UTC
