### ISSUE TITLE
Emoji Fix

### ISSUE THREAD

**Issue by FrequencyX4** [Aliucord/plugin-requests#422] opened 2021-12-01 17:22 UTC
### Discord Account

Luck#1574

### Plugin Description

a plugin to fix some emojis not parsing despite having access, the emoji not being locked, etc

### Go into more detail...

some emojis don't parse due to a discord bug that hasn't been fixed for months

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment] 2021-12-01 17:24
duplicate of #311

**Closed** 2021-12-01 17:23 UTC
Labels: up for grabs
