### ISSUE TITLE
Change attached file name during send

### ISSUE THREAD

**Issue by Excarius** [Aliucord/plugin-requests#530] opened 2022-01-14 15:14 UTC
### Discord Account

Kιokυ#2739

### Plugin Description

A plugin that renames any file attached, to be renamed into something customizable when sending.

If multiple files at one-time, could be added test-1.png test-2.png the "-x" extension if multiple files being sent simultaneously.

Filename customizatiom could be done through a slash command like "/filename test123" and it saves like that.

If possible, maybe a plugin setting panel to choose which extensions to be whitelisted for the file name change.

### Go into more detail...

Helps with privacy, could be done manually with file browser, but this plugin could save alot time for many.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by scrazzz** [comment] 2022-01-14 16:26
Duplicate of #327 and #472

**Closed** 2022-01-14 16:52 UTC
Labels: up for grabs
