### ISSUE TITLE
Always make gifs playing

### ISSUE THREAD

**Issue by Federico-IT** [Aliucord/plugin-requests#113] opened 2021-07-29 23:40 UTC
### Discord Account

MaxData77#2131

### Plugin Description

A simple plugin that make always the gifs playing (animated server logo, animated pfp, etc...). And maybe add an option that allows to disable a specific gif, for example disable always animated pfp, but not the animated server logo. (Sorry for my bad english)

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by NatSepruko** [comment] 2021-07-29 23:42
Duplicate of #25

**Closed by NatSepruko** 2021-07-29 23:42 UTC
Labels: up for grabs
