### ISSUE TITLE
Markdown for #, ##, and ###

### ISSUE THREAD

**Issue by Thick9035** [Aliucord/plugin-requests#1362] opened 2024-04-22 18:04 UTC
### Discord Account

deathbaby_.31

### Plugin Description

A plugin that allows you to see the text sizes of #, ##, and ###

### Go into more detail...

Aliucord doesn't allow the usage of #, ##, and ###, so this would be a cool feature to see in a plugin.

### Request Agreement

- [x] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by PiRhoRAMPAGE** [comment] 2024-10-07 17:39
Also for -#

**Comment by jedenastka** [comment] 2024-11-01 10:13
Duplicate of #1071.

**Closed as not planned by jedenastka** 2024-11-01 10:13 UTC
