### ISSUE TITLE
More desktop-like layout for tablets, Chromebooks and other big-screened devices

### ISSUE THREAD

**Issue by estyseesghosts** [Aliucord/plugin-requests#624] opened 2022-02-11 05:34 UTC
### Plugin Description

I just installed the android version of discord on my chromebook since the webapp is pretty slow for me. While definitely being faster, it looks just like the phone app if you stretched it out. I basically just want a plugin to forcibly show all three "panels" (server and channel list, the chat and the member list) all the time.

### Go into more detail...

Not really a strict requirement for me but I think it could be useful for some other people, being able to toggle either panel (only having the server/channel list, or only having the member list) or being able to collapse the channel list while still having the server list visible.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by vortck** [comment] 2022-02-11 05:35
![image](https://user-images.githubusercontent.com/66898996/153542507-4dba0a10-0def-473c-8d56-af39ce4e9cbe.png)
Forgot to put this in the post but it's pretty bad...

**Comment by ItzOnlyAnimal** [comment] 2022-02-11 07:21
Why not use the web version of discord with something like goosemod?

(whoever takes this request will have lots of fun i can tell)

**Comment by vortck** [comment] 2022-02-11 07:45
> Why not use the web version of discord with something like goosemod?
> 
> (whoever takes this request will have lots of fun i can tell)

> since the webapp is pretty slow for me

**Comment by Vendicated** [comment] 2022-03-08 11:40
Duplicate of #382

**Closed by Vendicated** 2022-03-08 11:40 UTC
Labels: up for grabs
