### ISSUE TITLE
Copy role

### ISSUE THREAD

**Issue by DHOT112233** [Aliucord/plugin-requests#1267] opened 2023-12-12 09:12 UTC
### Discord Account

Dhotdhot

### Plugin Description

Please, bro, add a copyrole plugin like the channel copy plugin so that it's easy if you want to create a lot of roles 

### Go into more detail...

Please, bro, add a copyrole plugin like the channel copy plugin so that it's easy if you want to create a lot of roles 

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by jedenastka** [comment] 2024-12-07 02:23
Duplicate of #885.

**Closed as not planned by jedenastka** 2024-12-07 02:23 UTC
