### ISSUE TITLE
custom voice message audio

### ISSUE THREAD

**Issue by PillarGaming** [Aliucord/plugin-requests#1346] opened 2024-04-05 18:44 UTC
### Plugin Description

very self explanatory
just make being able to use audio files from storage as voice messages
would be really funny

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by jedenastka** [comment] 2024-11-14 11:19
Duplicate of #1141.

**Closed as not planned by jedenastka** 2024-11-14 11:19 UTC
