### ISSUE TITLE
DiscordActivities

### ISSUE THREAD

**Issue by Kpgamerx** [Aliucord/plugin-requests#745] opened 2022-04-02 21:02 UTC
### Plugin Description

Allows you to play Discord's Activity Games (Such as watching YouTube together and Chess) with friends in voice chats.like discord desktop 

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by zt64** [comment] 2022-04-02 21:12
Duplicate of #623

**Closed** 2022-04-02 21:12 UTC
Labels: up for grabs
