### ISSUE TITLE
View Full Screenshare Previews Without Joining Call

### ISSUE THREAD

**Issue by D3C0D3R5** [Aliucord/plugin-requests#27] opened 2021-05-29 03:45 UTC
### Description
The ability to see the best quality preview of what someone is screensharing without having to join the call.

### More info
Pressing the 3 dots on the top right of someone profile (if they are screensharing) would bring up a "Copy Screenshare Image URL" button. Once pressed, it would copy the URL of the screenshare preview to your clipboard, ready to be pasted in a browser on someones chat to see in better quality.

---

- [x] I checked if this plugin wasn't already requested.

**Comment by WinstonSepruko** [comment] 2021-05-29 03:47
Closed as duplicate of #26.

**Closed by WinstonSepruko** 2021-05-29 03:47 UTC
Labels: duplicate, rejected
