### ISSUE TITLE
 Mobile audio file embeds

### ISSUE THREAD

**Issue by hexa69** [Aliucord/plugin-requests#415] opened 2021-11-24 18:27 UTC
### Discord Account

hexa#6666

### Plugin Description

I have an idea for plugin, that adds embeds like on pc for music files,  i mean you can play audio files without downloading them, directly on discord.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment] 2022-03-21 15:16
Duplicate of #105

**Closed by Vendicated** 2022-03-21 15:16 UTC
Labels: up for grabs
