### ISSUE TITLE
FileToVoiceMessages Or BetterVoiceMessages

### ISSUE THREAD

**Issue by GlockFatherDraco** [Aliucord/plugin-requests#1429] opened 2024-09-11 02:19 UTC
### Discord Account

_8jn

### Plugin Description

> an updated voice messages plugin that turns files ( mp3, mp4 if possible, wav, etc..) into a Voice Message or makes ||tts voice messages||

### Go into more detail...

> Make a plugin that turns files into discord voice messages or make an updated version of the voice messages plugin and make the voice messages button splits into 2 ||3 (optional)|| buttons when pressed.

* 1st button is normal voice button
* 2nd button is the files to voice
* ||3rd button is tts ( optional)||

>And also some fixes for the plugin because some times it glitches out and doesn't let me stop recording

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by awes956** [comment] 2024-11-14 10:48
I think someone can do it, but You might need to wait alot longer now

**Comment by jedenastka** [comment] 2024-11-14 11:20
Duplicate of #1141.

**Closed as not planned by jedenastka** 2024-11-14 11:20 UTC
