### ISSUE TITLE
View Deleted Messages

### ISSUE THREAD

**Issue by xRqz3r** [Aliucord/plugin-requests#75] opened 2021-07-04 09:18 UTC
### Discord Account

! xRqz3r#0020

### Plugin Description

I think a plugin like View Deleted Messages is a must have. In Simple terms, let's you view deleted messages as the title explains itself. 

### Go into more detail...

What is View Deleted Messages? - Basically what I'm suggesting is for anyone to create a plugin which allows for the user to view any deleted messages, either from other people or yourself. The message could be saved to a small database or something and if another person deletes their message or you delete your message it will still show up and allow you to see it. This allows for us to see the message that people who ghost ping or people who just delete their message after saying a racist slur.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by WinstonSepruko** [comment] 2021-07-04 09:19
Duplicate of #10

**Closed by WinstonSepruko** 2021-07-04 09:19 UTC
Labels: up for grabs
