### ISSUE TITLE
Webhooks in mobile

### ISSUE THREAD

**Issue by cateee69** [Aliucord/plugin-requests#268] opened 2021-09-26 19:37 UTC
### Discord Account

No response

### Plugin Description

I think of a plugin that allows you to access/manage webhook in the mobile client
(Idk if its possible ) but regardless to say it will save a lot of time 

### Go into more detail...

.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Juby210** [comment] 2021-09-26 19:38
duplicate of #125

**Closed by Juby210** 2021-09-26 19:38 UTC
Labels: up for grabs
