### ISSUE TITLE
Add friends by usernames/handles

### ISSUE THREAD

**Issue by Infisreal** [Aliucord/plugin-requests#1238] opened 2023-10-26 08:00 UTC
### Discord Account

Infisrael

### Plugin Description

A plugin that lets you friend people with usernames/handles instead of just tags.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by jedenastka** [comment] 2024-11-01 15:04
Duplicate of #1120.

**Closed as not planned by jedenastka** 2024-11-01 15:04 UTC
