### ISSUE TITLE
Super reactions?

### ISSUE THREAD

**Issue by echerwrecker** [Aliucord/plugin-requests#1264] opened 2023-12-10 09:52 UTC
### Plugin Description

Super reactions could be cool

### Go into more detail...

I'm sure you guys can find a way to make this work, maybe even add the animations from base discord?

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by echerwrecker** [comment] 2023-12-10 09:53
discord* autocorrect

**Comment by jedenastka** [comment] 2024-02-15 01:58
Duplicate of #1219.

**Closed as not planned** 2024-02-15 01:58 UTC
