### ISSUE TITLE
Ping random @someone

### ISSUE THREAD

**Issue by moko456** [Aliucord/plugin-requests#567] opened 2022-01-21 09:18 UTC
### Discord Account

moko#1000

### Plugin Description

i dont really know if this is possible but, a plugin ive heard in powercord or somewhere i think, a plugin was made where a mention  @someone which pings a random person, it seems ridiculous but maybe you guys could make it? hope its possible. thanks!

### Go into more detail...

a mention (@someone) which pings a random person on a server or group..

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment] 2022-01-21 09:24
duplicate of #24

**Closed by Vendicated** 2022-01-21 09:24 UTC
Labels: up for grabs
