### ISSUE TITLE
URGENT: LABELS FOR THE FUNCTIONAL FORUMS IN THE OLD VERSION OF DISCORD

### ISSUE THREAD

**Issue by MarddleDoo12** [Aliucord/plugin-requests#1094] opened 2023-06-05 11:39 UTC
### Discord Account

Marddle(Simp de Yuri)#3021

### Plugin Description

It would be incredible if the tags used in the forums would work, for example:
>Traditional drawings
>digital drawings
Since it works in the new version, but in the old one they don't appear, causing some problems.

### Go into more detail...

Those tags that appear when creating a forum on a server, in many servers it is mandatory to create a forum with some tag, so it is not created in the old version.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by rushiiMachine** [comment] 2023-06-05 13:38
duplicate of #1081

**Closed as not planned by rushiiMachine** 2023-06-05 13:38 UTC
