### ISSUE TITLE
Crypto-cord💀

### ISSUE THREAD

**Issue by Asimoposting** [Aliucord/plugin-requests#557] opened 2022-01-18 18:41 UTC
### Discord Account

Asimo#2810

### Plugin Description

A plugin that makes you see how much cost a crypto, at least only bitcoin
(with slash command) 

### Go into more detail...

There are so many idiot plugins so this is good

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by scrazzz** [comment] 2022-01-18 18:42
Duplicate of #377

**Closed** 2022-01-18 18:45 UTC
Labels: up for grabs
