### ISSUE TITLE
Move channels

### ISSUE THREAD

**Issue by AhadEA** [Aliucord/plugin-requests#394] opened 2021-11-17 12:25 UTC
### Discord Account

ੴ cobalt ριЖιs#6080

### Plugin Description

Move channels to up and down.

### Go into more detail...

A plugin for moving text channels to up or down with press and hold or with a move to up and down button that show when you hold the channel.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by fym35** [comment] 2021-11-17 13:19
Duplicate of #384

**Comment by fym35** [comment] 2021-11-17 13:20
Wait

**Comment by fym35** [comment] 2021-11-17 13:21
It isnt because that one is LOCAL and this one isnt

**Comment by Juliaxe** [comment] 2021-11-17 15:10
This is already a stock feature within Server Settings.

**Comment by Reinified** [comment] 2021-11-18 14:56
stock discord mobile feature
close now now now

**Closed** 2022-01-06 19:19 UTC
Labels: up for grabs
