### ISSUE TITLE
Send friend request to non-tag usernames

### ISSUE THREAD

**Issue by Function0x1** [Aliucord/plugin-requests#1259] opened 2023-12-09 08:46 UTC
### Discord Account

function_0x

### Plugin Description

The title is enough.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by zt64** [comment] 2024-04-20 08:52
Duplicate of #1238

**Closed as not planned by zt64** 2024-04-20 08:52 UTC
