### ISSUE TITLE
Favorited channels/DMs

### ISSUE THREAD

**Issue by vooktm** [Aliucord/plugin-requests#672] opened 2022-02-28 18:21 UTC
### Discord Account

gber#9177

### Plugin Description

A plugin that mimics the desktop/web experimental favorited channels/DMs section, but for mobile. 

### Go into more detail...

Holding down on a DM or channel gives a new option called "Favorite channel" or "Favorite DM" If a channel or DM is already favorited, the option will say "Unfavorite channel" or "Unfavorite DM". Once favorited, the channel or DM appears in a new section titled "Favorites" (below the home section). The layout is similar to that of a server, but you can access the DMs/channels you favorited from within the favorites section, including voice channels. The DMs have a small image of the user next to them. Holding down on a favorited channel will give you an option called "go to server", where it takes you to the server that channel belongs to while keeping you in the same channel. You can hide muted channels and create categories in the favorites section as well (via the server dropdown). If possible, pings will notify you in the favorites section, and it will have an unread indicator. 

For reference, here is a picture of the current Discord-made favorites page (sorry for quality, might need to be opened in new tab): 
![FavChannels DMs](https://user-images.githubusercontent.com/49358729/156034656-bf9ecfb7-847c-4242-aa9c-37bcea1c73a8.jpg)

If you have any questions, concerns, or need more info, feel free to ping me. 

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by zt64** [comment] 2022-02-28 18:24
You will install DMCategories

**Comment by vooktm** [comment] 2022-02-28 18:32
> You will install DMCategories

It is separate from DMCategories, as it has additional features that DMCategories does not include. Maybe integrate DMCategories then?

**Comment by DiamondMiner88** [comment] 2022-02-28 18:43
Duplicate of #622

**Comment by vooktm** [comment] 2022-02-28 18:56
> Duplicate of #622

shit, sorry. Nothing came up when I searched so I assumed I was fine.

**Closed** 2022-03-01 11:35 UTC
Labels: up for grabs
