### ISSUE TITLE
Image Utilities  

### ISSUE THREAD

**Issue by Dxrkz1** [Aliucord/plugin-requests#218] opened 2021-09-08 16:26 UTC
### Discord Account

DaddyZenith#0002

### Plugin Description

Ok so I want to say that can someone make a plugin that search for images/videos online You right click a image/video Then press search in (Browser) And it opens the results for that image. 

Idea from this better discord plugin -https://betterdiscord.app/plugin/ImageUtilities

### Go into more detail...

I need a plugin that can search for images/videos online, so You right click a image/video and Then press search in (Browser) And it opens the results for that image. 

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Reinified** [comment] 2021-09-21 18:07
when you tap on an image or video, it has a little browser option in the top left that opens your main browser, depending on what browser you use just hold on the image/video and press Search Google.
![image](https://user-images.githubusercontent.com/54984650/134224318-c778ba06-796a-426d-9f5c-4dde05376477.png)

**Comment by TymanWasTaken** [comment] 2021-11-15 02:22
this is a duplicate of #186 which is done

**Comment by Reinified** [comment] 2021-11-16 01:57
is someone going to close this since its done and a duplicate, or is it just going to stay open :husk:

**Closed** 2021-11-21 20:44 UTC
Labels: duplicate, completed
