### ISSUE TITLE
@silent backport

### ISSUE THREAD

**Issue by headassbtw** [Aliucord/plugin-requests#1226] opened 2023-10-08 07:54 UTC
### Discord Account

headassbtw

### Plugin Description

discord rolled out a feature that disables audio/notifs for a ping or DM but still pings/DMs them if you preface the message with `@silent`

this would be nice to have, notably/exclusively the no push notifs part (maybe mark as silent in android? idk if that's possible) but idk how feasible that is (idk how android apps handle notifications)

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by jedenastka** [comment] 2024-11-01 15:06
Duplicate of #1054.

**Closed as not planned** 2024-11-01 15:06 UTC
