### ISSUE TITLE
Local arrange server channels 

### ISSUE THREAD

**Issue by RejectedSmile** [Aliucord/plugin-requests#1177] opened 2023-08-29 23:07 UTC
### Discord Account

rejectedsm

### Plugin Description

I think it would be useful to be able to move the text and voice channels that you frequent in a server to the top or in a easier to find location.

### Go into more detail...

So if you long press on a Chanel there should be an option like local move and you can pick where I goes for you.

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by jedenastka** [comment] 2024-11-02 12:29
Duplicate of #384.

[FavoriteChannels](https://discord.com/channels/811255666990907402/845784407846813696/1284268357658476638) might do the trick here though.

**Closed as not planned by jedenastka** 2024-11-02 12:29 UTC
